---
deployment:
  tasks:
    # Instalar dependencias y construir la aplicación
    - npm install
    - ng build --configuration=production
    
    # Configurar el directorio de despliegue
    - export DEPLOYPATH=/home/example/public_html/
    
    # Copiar los archivos construidos
    - /bin/cp -R dist/orasystem-angular/* $DEPLOYPATH
    
    # Crear archivo .htaccess para manejar rutas de Angular
    - echo "RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]" > $DEPLOYPATH/.htaccess 